server:
  port: 8080
  time-zone: UTC
  servlet:
    context-path: /api

spring:
  profiles:
    active: local

  jpa:
    openInView: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub
        registration:
          google:
            scope: openid, profile, email
            redirect-uri: ${application.host}api/login/oauth2/code/google
          azure:
            provider: azure-ad
            authorization-grant-type: authorization_code
            scope: openid, profile, email, user.read
            redirect-uri: ${application.host}api/login/oauth2/code/azure

  flyway:
    outOfOrder: true
    locations: classpath:db/migration
    validate-on-migrate: false
    enabled: true

application:
  name: AURA Auth
  security:
    send-code-rate: 60 #seconds
    token:
      expiration:
        - scope: FULL_ACCESS
          access: 86400000 # 1 day
          refresh: 2592000000 # 30 days
        - scope: TWO_FACTOR_REQUIRED
          access: 600000 # 10 minutes
        - scope: CONFIRMATION_REQUIRED
          access: 600000 # 10 minutes

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true